#!/usr/bin/env sh
# Make a local copy of the custom recipes from our
# conan-center-index fork, so that we don't have to clone it in CI

SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
cd $SCRIPTPATH

# Custom recipes hopefully to be upstreamed

RECIPES=("xorg" "sdl" "libglvnd")

for recipe in "${RECIPES[@]}"; do
    echo "! Removing $recipe"
    [ -d "./$recipe" ] && rm -r "$recipe"

    echo "Updating $recipe"
    cp -r "../conan-center-index/recipes/$recipe" .
    [ -d "./$recipe" ] && touch "./$recipe/_AUTOGENERATED"
done
