name: test
on:
  pull_request:
    branches:
      - 'main'
      - 'dev'

jobs:
  build:
    uses: './.github/workflows/build.yml'
  test:
    runs-on: 'ubuntu-20.04'
    needs: build
    steps:
      - run: echo tests here
